### ISSUE TITLE
Mathematical notation should be unified

### ISSUE THREAD

**Issue by microbecode** [RareSkills/zk-book#3]
The first chapter uses $$ character for writing mathematical variables and equations, like $a = 0$. The second chapter use ``, like `a = 0`. 

Unsure what other chapters use.

These should be unified across all chapters. But someone needs to decide the "correct" notation first.

**Comment by RareSkills** [comment]
When the context is a variable in source code, it should be `a = 0`. When the context is "math" (no reference to code) it should be $a = 0$.

The old website did not support math notation, so there was no option for $a = 0$ and it always had to be `a = 0`.

**Comment by TakeASwing-420** [comment]
in the groth-16.md the right hand side's upper limit is from 1 to n but it should be 1 to m..I think

**Comment by RareSkills** [comment]
@TakeASwing-420 you're correct -- we've merged your pull request for that.

**Comment by TakeASwing-420** [comment]
@RareSkills thanks...also I would request you to review the pull request #10

**Comment by RareSkills** [comment]
@TakeASwing-420 good PR, we left a small comment for what needs to change with it.
