### ISSUE TITLE
Second half of the Introduction to ZK Bulletproofs post is not properly formatted 

### ISSUE THREAD

**Issue by marcobesier** [RareSkills/zk-book#41]
While the Markdown preview of the post looks correct on GitHub, the second half of the [Introduction to ZK Bulletproofs](https://www.rareskills.io/post/bulletproofs-zk) chapter is not rendered correctly on the website.

**Comment by tanim0la** [comment]
@marcobesier can you be more specific?

**Comment by marcobesier** [comment]
Not sure why, but the issue seems to have disappeared. I wasn't more specific because literally the entire second half of the post was messed up when I looked at it. Anyway.. For whatever reason, the problem's solved now. :D
