### ISSUE TITLE
Right hand side upper limit issue in Groth16 verification algorithm

### ISSUE THREAD

**Issue by TakeASwing-420** [RareSkills/zk-book#7]
The right hand side upper limit should be set to _m_ instead of _n_ in the [groth16.md](https://github.com/RareSkills/zk-book/blob/7e546306114fc67ed028124ba6006710cb28cf1a/content/groth16/en/groth16.md#groth16-explained)
[Link to the issue](https://github.com/RareSkills/zk-book/blob/7e546306114fc67ed028124ba6006710cb28cf1a/content/groth16/en/groth16.md?plain=1#L32)

**Comment by RareSkills** [comment]
Closing with this merge: https://github.com/RareSkills/zk-book/pull/8

Thanks for your contribution!
